// Runtime do modo TEST (juiz de código): expõe globals test/it/expect/describe,
// roda o código do usuário e devolve verde/vermelho por asserção. Roda em
// `sandbox="allow-scripts"` (origem opaca), sem React. Novo no protocolo:
//   iframe → pai  { type: 'deck:test', results: [{name, pass, error}] }
// Reaproveita deck:ready/error/height/log. Só assíncrono simples não é suportado.
export const IFRAME_HTML_TEST = [
  '<!doctype html><html><head><meta charset="utf-8" />',
  '<style>html,body{margin:0;padding:12px;background:#0c0c0c;color:#e5e7eb;',
  'font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px;line-height:1.5}',
  '.pass{color:#4ade80}.fail{color:#f87171}.name{color:#d4d4d4}.msg{color:#f87171;padding-left:18px;white-space:pre-wrap}',
  '.sum{margin-top:10px;padding-top:8px;border-top:1px solid #262626;color:#a3a3a3}',
  '#err{color:#dc2626;white-space:pre-wrap}</style></head><body>',
  '<div id="out"></div><div id="err"></div>',
  '<script>',
  'var out=document.getElementById("out");var errEl=document.getElementById("err");',
  'function post(m){window.parent.postMessage(m,"*");}',
  'function msgOf(e){return String(e&&e.message?e.message:e);}',
  'function showErr(m){errEl.textContent=m;post({type:"deck:error",message:m});}',
  'function fmtArg(v){if(typeof v==="string")return v;if(v instanceof Error)return v.message;try{var s=JSON.stringify(v);return s===undefined?String(v):s;}catch(e){return String(v);}}',
  '["log","info","warn","error","debug"].forEach(function(level){var orig=console[level];console[level]=function(){var a=[];for(var i=0;i<arguments.length;i++)a.push(fmtArg(arguments[i]));post({type:"deck:log",level:level==="debug"?"log":level,text:a.join(" ")});if(orig)orig.apply(console,arguments);};});',
  'window.addEventListener("error",function(e){showErr(msgOf(e.error||e.message));});',
  'function reportHeight(){post({type:"deck:height",height:document.documentElement.scrollHeight});}',
  // eq: igualdade estrutural tolerante (arrays/objetos), suficiente pro juiz.
  'function eq(a,b){if(a===b)return true;if(typeof a!=="object"||typeof b!=="object"||!a||!b)return false;',
  '  var ka=Object.keys(a),kb=Object.keys(b);if(ka.length!==kb.length)return false;',
  '  for(var i=0;i<ka.length;i++){if(!eq(a[ka[i]],b[ka[i]]))return false;}return true;}',
  'function fmt(v){try{return JSON.stringify(v);}catch(e){return String(v);}}',
  'function expect(actual){',
  '  function assert(cond,msg){if(!cond)throw new Error(msg);}',
  '  var api={',
  '    toBe:function(e){assert(actual===e,"esperava "+fmt(e)+", recebeu "+fmt(actual));},',
  '    toEqual:function(e){assert(eq(actual,e),"esperava (deep) "+fmt(e)+", recebeu "+fmt(actual));},',
  '    toBeTruthy:function(){assert(!!actual,"esperava truthy, recebeu "+fmt(actual));},',
  '    toBeFalsy:function(){assert(!actual,"esperava falsy, recebeu "+fmt(actual));},',
  '    toBeGreaterThan:function(e){assert(actual>e,"esperava > "+fmt(e)+", recebeu "+fmt(actual));},',
  '    toBeLessThan:function(e){assert(actual<e,"esperava < "+fmt(e)+", recebeu "+fmt(actual));},',
  '    toContain:function(e){assert(actual&&actual.indexOf(e)!==-1,fmt(actual)+" não contém "+fmt(e));},',
  '    toThrow:function(){var t=false;try{actual();}catch(x){t=true;}assert(t,"esperava que lançasse erro");}',
  '  };',
  '  api.not={toBe:function(e){assert(actual!==e,"não esperava "+fmt(e));},',
  '    toEqual:function(e){assert(!eq(actual,e),"não esperava (deep) "+fmt(e));},',
  '    toContain:function(e){assert(!(actual&&actual.indexOf(e)!==-1),fmt(actual)+" contém "+fmt(e));}};',
  '  return api;',
  '}',
  'function runTests(code){',
  '  errEl.textContent="";out.innerHTML="";',
  '  var results=[];',
  '  function test(name,fn){var r={name:String(name),pass:true,error:""};try{fn();}catch(e){r.pass=false;r.error=msgOf(e);}results.push(r);}',
  '  var describe=function(_,fn){fn();};',
  '  var fn=new Function("test","it","expect","describe","console",code);',
  '  fn(test,test,expect,describe,console);',
  '  var passed=0;',
  '  results.forEach(function(r){',
  '    var row=document.createElement("div");',
  '    row.innerHTML="<span class=\\""+(r.pass?"pass":"fail")+"\\">"+(r.pass?"✓":"✗")+"</span> <span class=name>"+r.name+"</span>";',
  '    out.appendChild(row);',
  '    if(r.pass)passed++;else{var m=document.createElement("div");m.className="msg";m.textContent=r.error;out.appendChild(m);}',
  '  });',
  '  var sum=document.createElement("div");sum.className="sum";',
  '  sum.textContent=results.length?(passed+"/"+results.length+" passaram"):"nenhum test() encontrado — use test(\\"nome\\", ()=>{ expect(x).toBe(y) })";',
  '  out.appendChild(sum);',
  '  post({type:"deck:test",results:results});',
  '  requestAnimationFrame(function(){setTimeout(reportHeight,0);});',
  '}',
  'window.addEventListener("message",function(e){',
  '  if(!e.data||e.data.type!=="deck:code")return;',
  '  try{runTests(e.data.code);}catch(err){showErr(msgOf(err));}',
  '});',
  'post({type:"deck:ready"});',
  '</script></body></html>',
].join('');
