// Documento do iframe de preview NATIVO (react-native-web). Mesma política de
// sandbox do preview web (`allow-scripts`, origem opaca), mas o require shim
// mapeia `react-native` / `react-native-web` pro bundle vendorado — então o
// assistente escreve componentes RN de verdade (View, Text, Pressable,
// StyleSheet) e eles rodam no navegador, sem macOS. Sem Tailwind: RN usa
// StyleSheet. O #root preenche a tela do telefone (flex:1 dos Views precisa de
// pai com altura).
export const IFRAME_HTML_NATIVE = [
  '<!doctype html><html><head><meta charset="utf-8" />',
  '<script src="/vendor/react.production.min.js"></script>',
  '<script src="/vendor/react-dom.production.min.js"></script>',
  '<script src="/vendor/react-native-web.js"></script>',
  '<style>html,body,#root{margin:0;height:100%;width:100%}',
  'body{font-family:ui-sans-serif,system-ui,sans-serif;background:#fff}',
  '#root{display:flex}#root>*{flex:1}',
  '#err{position:absolute;inset:0;padding:12px;color:#dc2626;font-family:ui-monospace,monospace;font-size:13px;white-space:pre-wrap;background:#fff}',
  '#err:empty{display:none}</style>',
  '</head><body>',
  '<div id="root"></div><div id="err"></div>',
  '<script>',
  'var mountEl=document.getElementById("root");',
  'var errEl=document.getElementById("err");',
  'var RNW=window.ReactNativeWeb;var root=null;',
  'function post(m){window.parent.postMessage(m,"*");}',
  'function msgOf(e){return String(e&&e.message?e.message:e);}',
  'function showErr(m){errEl.textContent=m;post({type:"deck:error",message:m});}',
  'function reqShim(name){',
  '  if(name==="react")return React;',
  '  if(name==="react-dom"||name==="react-dom/client")return ReactDOM;',
  '  if(name==="react-native"||name==="react-native-web")return RNW;',
  '  throw new Error("módulo indisponível no preview: "+name);',
  '}',
  'window.addEventListener("error",function(e){showErr(msgOf(e.error||e.message));});',
  'function evalCode(code){',
  '  var exports={};var module={exports:exports};',
  '  var fn=new Function("React","useState","useEffect","useRef","useMemo","useCallback","require","exports","module",code);',
  '  fn(React,React.useState,React.useEffect,React.useRef,React.useMemo,React.useCallback,reqShim,exports,module);',
  '  var C=module.exports&&module.exports.default?module.exports.default:module.exports;',
  '  if(typeof C!=="function")throw new Error("O código precisa de um export default (componente).");',
  '  return C;',
  '}',
  'function renderCode(code){',
  '  errEl.textContent="";',
  '  var C=evalCode(code);',
  '  if(root){root.unmount();root=null;}',
  '  mountEl.innerHTML="";',
  '  root=ReactDOM.createRoot(mountEl);',
  '  root.render(React.createElement(C));',
  '}',
  'window.addEventListener("message",function(e){',
  '  if(!e.data)return;',
  '  if(e.data.type==="deck:code"){try{renderCode(e.data.code);}catch(err){showErr(msgOf(err));}}',
  '});',
  'post({type:"deck:ready"});',
  '</script></body></html>',
].join('');
