// Runtime do modo SVG: injeta o markup cru (que pode ter <style>, <animate>,
// SMIL ou CSS) centralizado sobre um xadrez de transparência — assim dá pra ver
// canais alfa. Roda em `sandbox="allow-scripts"` (origem opaca), sem React: SVG
// não precisa. Mesmo protocolo deck:html/ready/error/height/log do runtime web.
export const IFRAME_HTML_SVG = [
  '<!doctype html><html><head><meta charset="utf-8" />',
  '<style>',
  'html,body{margin:0;padding:0;height:100%}',
  'body{display:flex;align-items:center;justify-content:center;min-height:100vh;',
  'background-color:#fff;background-image:',
  'linear-gradient(45deg,#e5e7eb 25%,transparent 25%),linear-gradient(-45deg,#e5e7eb 25%,transparent 25%),',
  'linear-gradient(45deg,transparent 75%,#e5e7eb 75%),linear-gradient(-45deg,transparent 75%,#e5e7eb 75%);',
  'background-size:20px 20px;background-position:0 0,0 10px,10px -10px,-10px 0}',
  '#stage{max-width:100%}#stage svg{max-width:100%;height:auto;display:block}',
  '#err{position:fixed;top:0;left:0;right:0;color:#dc2626;background:#fff;font-family:ui-monospace,monospace;font-size:13px;white-space:pre-wrap;padding:8px}',
  '</style></head><body>',
  '<div id="stage"></div><div id="err"></div>',
  '<script>',
  'var stage=document.getElementById("stage");var errEl=document.getElementById("err");',
  'function post(m){window.parent.postMessage(m,"*");}',
  'function msgOf(e){return String(e&&e.message?e.message:e);}',
  'function showErr(m){errEl.textContent=m;post({type:"deck:error",message:m});}',
  'function fmtArg(v){if(typeof v==="string")return v;if(v instanceof Error)return v.message;try{var s=JSON.stringify(v);return s===undefined?String(v):s;}catch(e){return String(v);}}',
  '["log","info","warn","error","debug"].forEach(function(level){var orig=console[level];console[level]=function(){var a=[];for(var i=0;i<arguments.length;i++)a.push(fmtArg(arguments[i]));post({type:"deck:log",level:level==="debug"?"log":level,text:a.join(" ")});if(orig)orig.apply(console,arguments);};});',
  'window.addEventListener("error",function(e){showErr(msgOf(e.error||e.message));});',
  'function reportHeight(){post({type:"deck:height",height:document.documentElement.scrollHeight});}',
  'window.addEventListener("message",function(e){',
  '  if(!e.data||e.data.type!=="deck:html")return;',
  '  try{errEl.textContent="";stage.innerHTML=e.data.html;',
  '    requestAnimationFrame(function(){setTimeout(reportHeight,0);});',
  '  }catch(err){showErr(msgOf(err));}',
  '});',
  'post({type:"deck:ready"});',
  '</script></body></html>',
].join('');
